// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj5CzMuWAcO8ktWroBjzko6hIJOJx2wTE',
    appId: '1:148874965366:web:c647c683b73bd9f3930a57',
    messagingSenderId: '148874965366',
    projectId: 'financeapp-91ebd',
    authDomain: 'financeapp-91ebd.firebaseapp.com',
    storageBucket: 'financeapp-91ebd.firebasestorage.app',
    measurementId: 'G-PGXVKFC347',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8jTkHE7xV31JdCdG8zc45-tWRVIsHPdA',
    appId: '1:148874965366:android:e858ca894be98212930a57',
    messagingSenderId: '148874965366',
    projectId: 'financeapp-91ebd',
    storageBucket: 'financeapp-91ebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARXr95etUyTE_YxsliO5opCfQUWhivES8',
    appId: '1:148874965366:ios:e069075c95932886930a57',
    messagingSenderId: '148874965366',
    projectId: 'financeapp-91ebd',
    storageBucket: 'financeapp-91ebd.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARXr95etUyTE_YxsliO5opCfQUWhivES8',
    appId: '1:148874965366:ios:e069075c95932886930a57',
    messagingSenderId: '148874965366',
    projectId: 'financeapp-91ebd',
    storageBucket: 'financeapp-91ebd.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj5CzMuWAcO8ktWroBjzko6hIJOJx2wTE',
    appId: '1:148874965366:web:a441a49908443f54930a57',
    messagingSenderId: '148874965366',
    projectId: 'financeapp-91ebd',
    authDomain: 'financeapp-91ebd.firebaseapp.com',
    storageBucket: 'financeapp-91ebd.firebasestorage.app',
    measurementId: 'G-6FMMK454NS',
  );
}
